### ISSUE TITLE
error on ios

### ISSUE THREAD

**Issue by hungdev** [kikill95/react-native-vlc-player#16]
Please update example srouce folder.
<img width="418" alt="screen shot 2018-08-11 at 3 17 13 pm" src="https://user-images.githubusercontent.com/12009276/43989734-a9e9f908-9d79-11e8-8dc2-d320af8f7268.png">

**Comment by kikill95** [comment]
Hello, thank you for an issue
We are currently working on full redeveloping, we will keep you on updates

**Comment by hungdev** [comment]
@kikill95 thanks for your reply. I hope it will update soon.
